export const DIAGNOSIS_LIST = [
  "Chest pain",
  "Abdominal pain",
  "Shortness of breath",
  "Fever",
  "Weakness",
  "Fatigue",
  "Dizziness",
  "Syncope",
  "Altered mental status",
  "Pain unspecified",
  "Nausea",
  "Vomiting",
  "Diarrhea",
  "Constipation",
  "Headache",
  "Back pain",
  "Neck pain",
  "Flank pain",
  "Pelvic pain",
  "Body aches",
  "Acute coronary syndrome (ACS)",
  "STEMI",
  "NSTEMI",
  "Unstable angina",
  "Stable angina",
  "Heart failure exacerbation",
  "Hypertensive urgency",
  "Hypertensive emergency",
  "Atrial fibrillation",
  "Atrial flutter",
  "SVT",
  "Ventricular tachycardia",
  "Ventricular fibrillation",
  "Bradycardia",
  "Heart block",
  "Pericarditis",
  "Myocarditis",
  "Aortic dissection",
  "Peripheral vascular disease",
  "Deep vein thrombosis",
  "Pulmonary embolism",
  "Cardiogenic shock",
  "Upper respiratory infection",
  "Viral syndrome",
  "Bronchitis",
  "Pneumonia",
  "COVID-19",
  "Influenza",
  "Asthma exacerbation",
  "COPD exacerbation",
  "Respiratory failure",
  "Hypoxia",
  "Hypercapnia",
  "Pneumothorax",
  "Hemothorax",
  "Pleural effusion",
  "Pulmonary edema",
  "Aspiration pneumonia",
  "Migraine",
  "Tension headache",
  "Cluster headache",
  "Seizure",
  "Status epilepticus",
  "TIA",
  "Ischemic stroke",
  "Hemorrhagic stroke",
  "Subarachnoid hemorrhage",
  "Intracranial hemorrhage",
  "Concussion",
  "Traumatic brain injury",
  "Delirium",
  "Vertigo",
  "Bell palsy",
  "Guillain-Barre syndrome",
  "Meningitis",
  "Encephalitis",
  "Gastroenteritis",
  "Gastritis",
  "Peptic ulcer disease",
  "GI bleed",
  "Upper GI bleed",
  "Lower GI bleed",
  "Appendicitis",
  "Cholecystitis",
  "Cholelithiasis",
  "Pancreatitis",
  "Bowel obstruction",
  "Ileus",
  "Diverticulitis",
  "Hernia",
  "Mesenteric ischemia",
  "Hepatitis",
  "Liver failure",
  "Ascites",
  "Fecal impaction",
  "Urinary tract infection",
  "Pyelonephritis",
  "Nephrolithiasis",
  "Acute kidney injury",
  "Chronic kidney disease exacerbation",
  "Urinary retention",
  "Hematuria",
  "Dysuria",
  "Testicular pain",
  "Testicular torsion",
  "Epididymitis",
  "Pregnancy",
  "Ectopic pregnancy",
  "Miscarriage",
  "Vaginal bleeding",
  "Vaginitis",
  "Pelvic inflammatory disease",
  "Ovarian cyst",
  "Ovarian torsion",
  "Labor",
  "Postpartum complication",
  "Sepsis",
  "Septic shock",
  "Bacteremia",
  "Cellulitis",
  "Abscess",
  "Skin infection",
  "Osteomyelitis",
  "Septic arthritis",
  "Fever unknown origin",
  "Diabetic ketoacidosis",
  "Hyperosmolar hyperglycemic state",
  "Hypoglycemia",
  "Hyperglycemia",
  "Electrolyte imbalance",
  "Hyponatremia",
  "Hypernatremia",
  "Hypokalemia",
  "Hyperkalemia",
  "Thyroid storm",
  "Myxedema coma",
  "Adrenal crisis",
  "Anxiety",
  "Panic attack",
  "Depression",
  "Suicidal ideation",
  "Suicide attempt",
  "Psychosis",
  "Bipolar episode",
  "Agitation",
  "Hallucinations",
  "Alcohol intoxication",
  "Alcohol withdrawal",
  "Drug overdose",
  "Opioid overdose",
  "Benzodiazepine overdose",
  "Acetaminophen toxicity",
  "Salicylate toxicity",
  "Carbon monoxide poisoning",
  "Toxic ingestion",
  "Withdrawal syndrome",
  "Muscle strain",
  "Sprain",
  "Joint pain",
  "Arthritis",
  "Gout",
  "Fracture",
  "Dislocation",
  "Tendon injury",
  "Bursitis",
  "Motor vehicle collision injury",
  "Fall",
  "Head injury",
  "Facial trauma",
  "Chest trauma",
  "Abdominal trauma",
  "Pelvic trauma",
  "Extremity injury",
  "Laceration",
  "Contusion",
  "Abrasion",
  "Burn",
  "Crush injury",
  "Penetrating trauma",
  "Pediatric fever",
  "Febrile seizure",
  "Croup",
  "Bronchiolitis",
  "Otitis media",
  "Failure to thrive",
  "Pediatric vomiting",
  "Pediatric dehydration",
  "Otitis externa",
  "Sinusitis",
  "Pharyngitis",
  "Tonsillitis",
  "Epistaxis",
  "Dental pain",
  "Eye pain",
  "Conjunctivitis",
  "Corneal abrasion",
  "Foreign body eye",
  "Anemia",
  "Sickle cell crisis",
  "Thrombocytopenia",
  "Neutropenic fever",
  "Cardiac arrest",
  "Respiratory arrest",
  "Shock unspecified",
  "Multi organ failure",
  "Dehydration",
  "Chronic pain exacerbation",
  "Chest tightness",
  "Palpitations",
  "Near syncope",
  "Lightheadedness",
  "Generalized weakness",
  "Localized swelling",
  "Leg swelling",
  "Arm pain",
  "Shoulder pain",
  "Hip pain",
  "Knee pain",
  "Ankle pain",
  "Foot pain",
  "Hand pain",
  "Wrist pain",
  "Finger injury",
  "Toe injury",
  "Rash",
  "Pruritus",
  "Hives",
  "Allergic reaction",
  "Anaphylaxis",
  "Insect bite",
  "Animal bite",
  "Tick bite",
  "Lyme disease",
  "Heat exhaustion",
  "Heat stroke",
  "Hypothermia",
  "Frostbite",
  "Electrical injury",
  "Drowning",
  "Near drowning",
  "Choking",
  "Airway obstruction",
  "Foreign body ingestion",
  "Esophageal obstruction",
  "Rectal bleeding",
  "Hemoptysis",
  "Hematemesis",
  "Melena",
  "Jaundice",
  "Weight loss",
  "Weight gain",
  "Polyuria",
  "Polydipsia",
  "Nocturia",
  "Incontinence",
  "Urinary frequency",
  "Urinary urgency",
  "Groin pain",
  "Scrotal swelling",
  "Breast pain",
  "Breast mass",
  "Vaginal discharge",
  "Amenorrhea",
  "Dysmenorrhea",
  "Infertility concern",
  "Postmenopausal bleeding",
  "Seizure disorder",
  "Breakthrough seizure",
  "Confusion",
  "Memory loss",
  "Speech difficulty",
  "Vision loss",
  "Double vision",
  "Hearing loss",
  "Tinnitus",
  "Ear pain",
  "Nasal congestion",
  "Runny nose",
  "Loss of smell",
  "Loss of taste",
  "Sore throat",
  "Difficulty swallowing",
  "Hoarseness",
  "Neck swelling",
  "Lymphadenopathy",
  "Night sweats",
  "Chills",
  "Rigors",
  "General illness",
  "Medical screening exam",
  "Medication refill",
  "Wound check",
  "Suture removal",
  "Post operative pain",
  "Post operative infection",
  "Device complication",
  "Pacemaker issue",
  "Dialysis complication",
  "Transplant complication",
  "Immunocompromised state",
  "Cancer related pain",
  "Palliative care visit",
  "End of life care",
  "Social admission",
  "Homelessness issue",
  "Failure to cope",
  "Caregiver stress",
  "Elder abuse concern",
  "Child abuse concern",
  "Domestic violence",
  "Sexual assault",
  "Poisoning unknown",
  "Chemical exposure",
  "Radiation exposure",
  "Occupational exposure",
  "Needlestick injury",
  "Blood exposure",
  "Rabies exposure",
  "Tetanus exposure",
  "Travel related illness",
  "Altitude sickness",
  "Motion sickness",
  "Decompression sickness",
  "Barotrauma",
  "Space occupying lesion",
  "Mass unspecified",
  "Cyst unspecified",
  "Benign tumor",
  "Malignant tumor",
  "Metastatic disease",
  "Acute pain",
  "Chronic pain",
  "Right arm pain",
  "Left arm pain",
  "Right leg pain",
  "Left leg pain",
  "Upper extremity pain",
  "Lower extremity pain",
  "Right upper quadrant pain",
  "Left upper quadrant pain",
  "Right lower quadrant pain",
  "Left lower quadrant pain",
  "Periumbilical pain",
  "Epigastric pain",
  "Generalized abdominal tenderness",
  "Rebound tenderness",
  "Guarding abdomen",
  "Abdominal distension",
  "Bloating",
  "Early satiety",
  "Dyspepsia",
  "Heartburn",
  "Reflux symptoms",
  "Odynophagia",
  "Dysphagia solids",
  "Dysphagia liquids",
  "Regurgitation",
  "Hiccups",
  "Flatulence",
  "Rectal pain",
  "Anal fissure",
  "Hemorrhoids",
  "Perianal abscess",
  "Perirectal abscess",
  "Rectal foreign body",
  "Change in bowel habits",
  "Loose stools",
  "Watery diarrhea",
  "Bloody diarrhea",
  "Mucus in stool",
  "Chronic diarrhea",
  "Acute diarrhea",
  "Vomiting blood",
  "Bilious vomiting",
  "Projectile vomiting",
  "Dry heaving",
  "Post-tussive vomiting",
  "Persistent nausea",
  "Intermittent nausea",
  "Decreased appetite",
  "Increased appetite",
  "Cachexia",
  "Failure to gain weight",
  "Obesity",
  "Morbid obesity",
  "Deconditioning",
  "Exercise intolerance",
  "Claudication",
  "Cold extremity",
  "Warm swollen joint",
  "Joint stiffness",
  "Morning stiffness",
  "Limited range of motion",
  "Joint effusion",
  "Joint instability",
  "Muscle weakness focal",
  "Muscle weakness generalized",
  "Muscle cramping",
  "Muscle spasm",
  "Muscle rigidity",
  "Tremor",
  "Resting tremor",
  "Intention tremor",
  "Ataxia",
  "Unsteady gait",
  "Falls recurrent",
  "Difficulty walking",
  "Paralysis",
  "Hemiparesis",
  "Quadriparesis",
  "Numbness",
  "Tingling",
  "Paresthesia",
  "Hyperesthesia",
  "Hypoesthesia",
  "Burning sensation",
  "Electric shock sensation",
  "Loss of coordination",
  "Aphasia",
  "Dysarthria",
  "Facial droop",
  "Ptosis",
  "Anisocoria",
  "Photophobia",
  "Phonophobia",
  "Visual aura",
  "Scotoma",
  "Blurred vision",
  "Eye redness",
  "Eye discharge",
  "Eye swelling",
  "Eye itching",
  "Dry eyes",
  "Foreign body sensation eye",
  "Visual floaters",
  "Flashes of light",
  "Vision tunnel",
  "Complete vision loss",
  "Partial vision loss",
  "Ear fullness",
  "Ear discharge",
  "Vertigo positional",
  "Vertigo constant",
  "Imbalance",
  "Nausea with vertigo",
  "Hearing change",
  "Sudden hearing loss",
  "Chronic hearing loss",
  "Ringing ears",
  "Buzzing ears",
  "Ear popping",
  "Sinus pressure",
  "Facial pain sinus",
  "Post nasal drip",
  "Chronic cough",
  "Acute cough",
  "Productive cough",
  "Dry cough",
  "Wheezing",
  "Stridor",
  "Noisy breathing",
  "Labored breathing",
  "Apnea",
  "Orthopnea",
  "Paroxysmal nocturnal dyspnea",
  "Chest pressure",
  "Chest burning",
  "Chest stabbing pain",
  "Chest wall pain",
  "Reproducible chest pain",
  "Palpitations intermittent",
  "Palpitations persistent",
  "Irregular heartbeat",
  "Slow heartbeat",
  "Rapid heartbeat",
  "Syncope exertional",
  "Syncope vasovagal",
  "Syncope cardiac",
  "Near blackout",
  "Collapse",
  "Altered behavior",
  "Aggression",
  "Combative behavior",
  "Withdrawal behavior",
  "Flat affect",
  "Emotional distress",
  "Panic symptoms",
  "Fear episode",
  "Insomnia",
  "Hypersomnia",
  "Sleep disturbance",
  "Nightmares",
  "Sleepwalking",
  "Substance abuse",
  "Drug seeking behavior",
  "Medication side effect",
  "Adverse drug reaction",
  "Allergy medication",
  "Food allergy",
  "Environmental allergy",
  "Seasonal allergies",
  "Contact dermatitis",
  "Atopic dermatitis",
  "Seborrheic dermatitis",
  "Psoriasis flare",
  "Skin ulcer",
  "Pressure ulcer",
  "Non healing wound",
  "Wound infection",
  "Surgical wound complication",
  "Drainage wound",
  "Redness skin",
  "Skin swelling",
  "Skin warmth",
  "Skin discoloration",
  "Bruising spontaneous",
  "Easy bruising",
  "Bleeding gums",
  "Nose bleeding recurrent",
  "Heavy menstrual bleeding",
  "Intermenstrual bleeding",
  "Postcoital bleeding",
  "Pregnancy concern",
  "Possible pregnancy",
  "High risk pregnancy",
  "Decreased fetal movement",
  "Preterm labor concern",
  "Rupture membranes",
  "Vaginal pain",
  "Dyspareunia",
  "Testicular swelling",
  "Penile discharge",
  "Erectile dysfunction",
  "STD exposure",
  "STD symptoms",
  "HIV exposure",
  "Hepatitis exposure",
  "Fever persistent",
  "Fever recurrent",
  "",
  "",
  "Hyperthermia",
  "Hypothermia exposure",
  "Chills without fever",
  "",
  "Sepsis",
  "Bacteremia suspected",
  "",
  "",
  "Viral illness unspecified",
  "Bacterial infection unspecified",
  "Fungal infection unspecified",
  "Parasitic infection",
  "Tick borne illness",
  "",
  "Travelers diarrhea",
  "Malaria concern",
  "Tuberculosis concern",
  "COVID exposure",
  "Influenza like illness",
  "Respiratory infection unspecified",
  "Urinary infection unspecified",
  "Skin infection unspecified",
  "Soft tissue infection",
  "Bone infection",
  "Joint infection",
  "Eye infection",
  "Ear infection",
  "Sinus infection",
  "Throat infection",
  "Dental infection",
  "Gum infection",
  "Oral ulcer",
  "Cold sore",
  "Herpes outbreak",
  "Shingles",
  "Chickenpox",
  "Measles",
  "Mumps",
  "Rubella",
  "HPV infection",
  "STD unspecified",
  "Gonorrhea",
  "Chlamydia",
  "Syphilis",
  "Trichomoniasis",
  "Bacterial vaginosis",
  "Yeast infection",
  "Candidiasis",
  "Thrush",
  "UTI recurrent",
  "Kidney infection recurrent",
  "Bladder pain syndrome",
  "Interstitial cystitis",
  "Prostate pain",
  "Prostatitis",
  "Benign prostatic hyperplasia",
  "Urinary obstruction",
  "Kidney failure acute",
  "Kidney failure chronic",
  "Dialysis complication acute",
  "Fluid overload",
  "Volume depletion",
  "Electrolyte disturbance",
  "Acid base disorder",
  "Metabolic acidosis",
  "Metabolic alkalosis",
  "Respiratory acidosis",
  "Respiratory alkalosis",
  "Lactic acidosis",
  "Hypercalcemia",
  "Hypocalcemia",
  "Hypermagnesemia",
  "Hypomagnesemia",
  "Hyperphosphatemia",
  "Hypophosphatemia",
  "Endocrine disorder unspecified",
  "Diabetes uncontrolled",
  "Diabetes complication",
  "Insulin reaction",
  "Thyroid disorder unspecified",
  "Hyperthyroidism",
  "Hypothyroidism",
  "Adrenal insufficiency",
  "Cushing syndrome",
  "Pituitary disorder",
  "Hormonal imbalance",
  "Growth disorder",
  "Obesity related complication",
  "Malnutrition",
  "Vitamin deficiency",
  "Iron deficiency",
  "B12 deficiency",
  "Folate deficiency",
  "Coagulopathy",
  "Bleeding disorder",
  "Clotting disorder",
  "Hypercoagulable state",
  "DVT recurrent",
  "PE recurrent",
  "Stroke symptoms",
  "Stroke follow up",
  "TIA symptoms",
  "Neurologic deficit",
  "Chronic neurologic disorder",
  "Neurodegenerative disease",
  "Parkinsonism",
  "Multiple sclerosis",
  "ALS concern",
  "Neuropathy",
  "Peripheral neuropathy",
  "Diabetic neuropathy",
  "Radiculopathy",
  "Sciatica",
  "Spinal stenosis",
  "Disc herniation",
  "Spine fracture",
  "Back injury acute",
  "Back injury chronic",
  "Neck injury acute",
  "Whiplash",
  "Shoulder dislocation recurrent",
  "Joint dislocation recurrent",
  "Fracture open",
  "Fracture closed",
  "Stress fracture",
  "Pathologic fracture",
  "Bone pain",
  "Bone lesion",
  "Soft tissue mass",
  "Lump evaluation",
  "Swelling unspecified",
  "Edema generalized",
  "Edema localized",
  "Lymphedema",
  "Venous insufficiency",
  "Varicose veins",
  "Ulcer leg",
  "Diabetic foot ulcer",
  "Gangrene",
  "Tissue necrosis",
  "Compartment syndrome",
  "Cardiac symptom unspecified",
  "Respiratory symptom unspecified",
  "GI symptom unspecified",
  "GU symptom unspecified",
  "Neuro symptom unspecified",
  "Psych symptom unspecified",
  "Skin symptom unspecified",
  "Musculoskeletal symptom unspecified",
  "Injury unspecified",
  "Trauma unspecified",
  "Pain acute unspecified",
  "Pain chronic unspecified",
  "Swelling unspecified region",
  "Bleeding unspecified",
  "Infection unspecified site",
  "Inflammation unspecified",
  "Mass unspecified site",
  "Lesion unspecified",
  "Condition unspecified",
  "Follow up visit",
  "Reevaluation visit",
  "Return visit",
  "Repeat complaint",
  "Unresolved symptoms",
  "Worsening symptoms",
  "Improving symptoms",
  "Stable condition",
  "Observation visit",
  "Monitoring visit",
  "Screening visit",
  "Preventive visit",
  "Administrative visit",
  "Work clearance",
  "School clearance",
  "Sports clearance",
  "Medical clearance",
  "Preoperative evaluation",
  "Postoperative evaluation",
  "Second opinion",
  "Consultation visit",
  "Referral evaluation",
  "Diagnostic uncertainty",
  "Rule out condition",
  "Suspected condition",
  "Possible condition",
  "Probable condition",
  "Confirmed condition",
  "Chronic condition unspecified",
  "Acute condition unspecified"
] as const;